[Python Simple Linked List]: Added Example Diagrams
exercism/v3-files pull request #16
Opened 2022-05-08 17:36 UTC by BethanyG

- [x] SVG Diagram for Linked List Stack
- [x] SVG Diagram for Array-Based Stack

2022-05-08 17:46 UTC, BethanyG commented
Closing since these are not big files.  Uploading them to the Python repo instead.

2022-05-21 04:44 UTC, BethanyG commented
Reopening per comments on https://github.com/exercism/python/pull/3026.

2022-05-21 06:37 UTC, SaschaMann requested changes

2022-05-21 06:37 UTC, SaschaMann commented on .gitattributes
> -*.png filter=lfs diff=lfs merge=lfs -text
I think this needs to stay, and you also need to add svg files to be handled by git lfs for this to work as intended.

2022-05-21 07:43 UTC, SaschaMann commented
The files don't say "Stored with LFS", so I'm not sure this has worked correctly. Could you verify that you added them via git lfs?

This info is missing:

![grafik](https://user-images.githubusercontent.com/20866761/169641495-cb1b9a41-437b-4f61-9478-f952d21efaf5.png)

I can take a closer look in the evening otherwise.

2022-05-21 08:58 UTC, BethanyG commented
ok.  _hopefully_ I did it correctly this time!  

![2022-05-21_01-58-10](https://user-images.githubusercontent.com/5923094/169644162-4602f3a5-20eb-4d1f-afd3-2a4c66d3aed4.png)

2022-05-21 10:51 UTC, merged